
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:  [ "tumbleweed", "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Unit Tests
      run: rake test:unit
      # enable code coverage reporting
      env:
        COVERAGE: 1

  Rubocop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro: [ "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Rubocop
      run: rake check:rubocop

    - name: Shellcheck
      run: shellcheck docker/run.sh

  Package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:  [ "tumbleweed", "leap_latest" ]

    container:
      image: registry.opensuse.org/yast/head/containers_${{matrix.distro}}/yast-ruby

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Package Build
      run: yast-ci-ruby -o package

  # No API code in this package -> no Yardoc check
  # No translations in this package -> no pot check
  # No Perl code in this package -> no Perl syntax check
